# Translations template for oslo.vmware.
# Copyright (C) 2016 ORGANIZATION
# This file is distributed under the same license as the oslo.vmware
# project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2016.
#
#, fuzzy
msgid ""
msgstr ""
"Project-Id-Version: oslo.vmware 2.5.1.dev6\n"
"Report-Msgid-Bugs-To: https://bugs.launchpad.net/openstack-i18n/\n"
"POT-Creation-Date: 2016-04-21 06:18+0000\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.2.0\n"

#: oslo_vmware/api.py:312
#, python-format
msgid ""
"Current session: %(session)s is inactive; re-creating the session while "
"invoking method %(module)s.%(method)s."
msgstr ""

#: oslo_vmware/api.py:476
#, python-format
msgid "Lease: %(lease)s is in error state. Details: %(error_msg)s."
msgstr ""

#: oslo_vmware/api.py:483
#, python-format
msgid "Unknown state: %(state)s for lease: %(lease)s."
msgstr ""

#: oslo_vmware/exceptions.py:54
msgid "An unknown exception occurred."
msgstr ""

#: oslo_vmware/exceptions.py:67
msgid "exception message must not be a list"
msgstr ""

#: oslo_vmware/exceptions.py:70
msgid "details must be a dict"
msgstr ""

#: oslo_vmware/exceptions.py:145
msgid "fault_list must be a list"
msgstr ""

#: oslo_vmware/exceptions.py:178
msgid "VMware Driver configuration fault."
msgstr ""

#: oslo_vmware/exceptions.py:187
msgid "No default value for use_linked_clone found."
msgstr ""

#: oslo_vmware/exceptions.py:191
#, python-format
msgid "Missing parameter : %(param)s"
msgstr ""

#: oslo_vmware/exceptions.py:199
msgid "Resource already exists."
msgstr ""

#: oslo_vmware/exceptions.py:204
msgid "Cannot delete file."
msgstr ""

#: oslo_vmware/exceptions.py:209
msgid "File already exists."
msgstr ""

#: oslo_vmware/exceptions.py:214
msgid "File fault."
msgstr ""

#: oslo_vmware/exceptions.py:219
msgid "File locked."
msgstr ""

#: oslo_vmware/exceptions.py:224
msgid "File not found."
msgstr ""

#: oslo_vmware/exceptions.py:229
msgid "Invalid power state."
msgstr ""

#: oslo_vmware/exceptions.py:234
msgid "Invalid property."
msgstr ""

#: oslo_vmware/exceptions.py:239
msgid "No Permission."
msgstr ""

#: oslo_vmware/exceptions.py:244
msgid "Not Authenticated."
msgstr ""

#: oslo_vmware/exceptions.py:249
msgid "Entity has another operation in process."
msgstr ""

#: oslo_vmware/exceptions.py:253
msgid "Duplicate name."
msgstr ""

#: oslo_vmware/exceptions.py:257
msgid "Insufficient disk space."
msgstr ""

#: oslo_vmware/exceptions.py:261
msgid "VMware Tools is not running."
msgstr ""

#: oslo_vmware/exceptions.py:265
msgid "Managed object not found."
msgstr ""

#: oslo_vmware/exceptions.py:302
msgid "exception should be a subclass of VimException"
msgstr ""

#: oslo_vmware/image_transfer.py:167
#, python-format
msgid "Image: %s is in killed state."
msgstr ""

#: oslo_vmware/image_transfer.py:181
#, python-format
msgid "Image: %(image)s is in unknown state: %(state)s."
msgstr ""

#: oslo_vmware/image_transfer.py:190
#, python-format
msgid "Error occurred while writing image: %s"
msgstr ""

#: oslo_vmware/image_transfer.py:275
msgid "Error occurred during file read-write task."
msgstr ""

#: oslo_vmware/image_transfer.py:362
msgid "No image destination given."
msgstr ""

#: oslo_vmware/image_transfer.py:379
#, python-format
msgid ""
"Error occurred during image transfer with reader: %(reader)s and writer: "
"%(writer)s"
msgstr ""

#: oslo_vmware/rw_handles.py:87 oslo_vmware/objects/datastore.py:316
#, python-format
msgid "Invalid scheme: %s."
msgstr ""

#: oslo_vmware/rw_handles.py:110
#, python-format
msgid "Error occurred while opening URL: %s for reading."
msgstr ""

#: oslo_vmware/rw_handles.py:145
#, python-format
msgid ""
"Error occurred while creating HTTP connection to write to VMDK file with "
"URL = %s."
msgstr ""

#: oslo_vmware/rw_handles.py:227
msgid "Could not retrieve VMDK URL from lease info."
msgstr ""

#: oslo_vmware/rw_handles.py:284 oslo_vmware/rw_handles.py:407
#, python-format
msgid "Connection error occurred while writing data to %s."
msgstr ""

#: oslo_vmware/rw_handles.py:292 oslo_vmware/rw_handles.py:415
#, python-format
msgid "Error occurred while writing data to %s."
msgstr ""

#: oslo_vmware/rw_handles.py:556
#, python-format
msgid "Error occurred while reading data from %s."
msgstr ""

#: oslo_vmware/service.py:248
msgid "Error occurred while calling RetrievePropertiesEx."
msgstr ""

#: oslo_vmware/service.py:328
#, python-format
msgid "No such SOAP method %s."
msgstr ""

#: oslo_vmware/service.py:334
#, python-format
msgid "httplib error in %s."
msgstr ""

#: oslo_vmware/service.py:338
#, python-format
msgid "requests error in %s."
msgstr ""

#: oslo_vmware/service.py:349
#, python-format
msgid "Socket error in %s."
msgstr ""

#: oslo_vmware/service.py:354
#, python-format
msgid "Type error in %s."
msgstr ""

#: oslo_vmware/service.py:357
#, python-format
msgid "Exception in %s."
msgstr ""

#: oslo_vmware/objects/datacenter.py:23
msgid "Datacenter name cannot be None"
msgstr ""

#: oslo_vmware/objects/datacenter.py:25
msgid "Datacenter reference cannot be None"
msgstr ""

#: oslo_vmware/objects/datastore.py:68
msgid "Datastore name cannot be None"
msgstr ""

#: oslo_vmware/objects/datastore.py:70
msgid "Datastore reference cannot be None"
msgstr ""

#: oslo_vmware/objects/datastore.py:72
msgid "Invalid capacity"
msgstr ""

#: oslo_vmware/objects/datastore.py:75
msgid "Capacity is smaller than free space"
msgstr ""

#: oslo_vmware/objects/datastore.py:103
msgid "datacenter must be set to build url"
msgstr ""

#: oslo_vmware/objects/datastore.py:187
msgid "Datastore name cannot be empty"
msgstr ""

#: oslo_vmware/objects/datastore.py:192 oslo_vmware/objects/datastore.py:233
msgid "Path component cannot be None"
msgstr ""

#: oslo_vmware/objects/datastore.py:246
msgid "Datastore path cannot be empty"
msgstr ""

#: oslo_vmware/objects/datastore.py:329
#, python-format
msgid ""
"Error occurred while creating HTTP connection to write to file with URL ="
" %s."
msgstr ""

#: oslo_vmware/tests/test_exceptions.py:34
msgid "string"
msgstr ""

#: oslo_vmware/tests/test_exceptions.py:44
msgid "cause"
msgstr ""

